export const $highlightTriads = document.getElementById('highlight-triads')
export const $instrumentControl = document.getElementById("instrument-select")
export const $rootNoteControl = document.getElementById("root-note")
export const $scaleTypeControl = document.getElementById("scale-type")
export const $scaleSystemControl = document.getElementById("scale-system")
export const $chordSystemControl = document.getElementById("chord-system")